version: '3'

services:
  db:
    image: postgres:13.4-alpine
    container_name: 'DjangoImgAPI_DB'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build: .
    container_name: 'DjangoImgAPI_WEB'
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    
    depends_on:
      - db